group=com.infernalsuite.asp
aspApiVersion=4.2.0-SNAPSHOT
apiVersion=26.2
# TODO Have own build counter here
version=26.2.build.126-stable
mcVersion=26.2

paperRef=c646fafccfc89339257ef3286d6756d8f97624c9

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

org.gradle.jvmargs=-Xmx10g
