group=com.infernalsuite.asp
aspApiVersion=4.2.0-SNAPSHOT
apiVersion=26.2
# TODO Have own build counter here
version=26.2.build.119-stable
mcVersion=26.2

paperRef=bb09b431d24f586da72ee7c4aa2e8cff2b32a478

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

org.gradle.jvmargs=-Xmx10g
