group=com.infernalsuite.asp
aspApiVersion=4.2.0-SNAPSHOT
apiVersion=26.2
# TODO Have own build counter here
version=26.2.build.127-stable
mcVersion=26.2

paperRef=ad9a0347f55d7b1e6679d2497f385e7985781edd

org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=false

org.gradle.jvmargs=-Xmx10g
